- job:
    name: neutron-dynamic-routing-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/neutron-dynamic-routing-dsvm-functional/run.yaml
    post-run: playbooks/neutron-dynamic-routing-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/neutron-dynamic-routing
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$


- project:
    templates:
      - check-requirements
      - openstack-cover-jobs-neutron
      - openstack-lower-constraints-jobs-neutron
      - openstack-python-jobs-neutron
      - openstack-python3-ussuri-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-dynamic-routing-dsvm-functional
        - neutron-tempest-plugin-dynamic-routing
    gate:
      jobs:
        - neutron-dynamic-routing-dsvm-functional
        - neutron-tempest-plugin-dynamic-routing
    periodic:
      jobs:
        - legacy-periodic-neutron-dynamic-routing-dsvm-tempest-with-ryu-master-scenario-ipv4
